/** Standard GATT service and characteristic UUID → human-readable label. */
export const GATT_LABELS: Record<string, string> = {
  // ── Services ────────────────────────────────────────────────────────────────
  '1800': 'Generic Access',
  '1801': 'Generic Attribute',
  '1802': 'Immediate Alert',
  '1803': 'Link Loss',
  '1804': 'Tx Power',
  '1805': 'Current Time',
  '1806': 'Reference Time Update',
  '1807': 'Next DST Change',
  '1808': 'Glucose',
  '1809': 'Health Thermometer',
  '180A': 'Device Information',
  '180D': 'Heart Rate',
  '180E': 'Phone Alert Status',
  '180F': 'Battery',
  '1810': 'Blood Pressure',
  '1811': 'Alert Notification',
  '1812': 'Human Interface Device',
  '1813': 'Scan Parameters',
  '1814': 'Running Speed and Cadence',
  '1815': 'Automation IO',
  '1816': 'Cycling Speed and Cadence',
  '1818': 'Cycling Power',
  '1819': 'Location and Navigation',
  '181A': 'Environmental Sensing',
  '181B': 'Body Composition',
  '181C': 'User Data',
  '181D': 'Weight Scale',
  '181F': 'Continuous Glucose Monitoring',
  '1822': 'Pulse Oximeter',

  // ── Characteristics ─────────────────────────────────────────────────────────
  '2A00': 'Device Name',
  '2A01': 'Appearance',
  '2A04': 'Peripheral Preferred Connection Parameters',
  '2A05': 'Service Changed',
  '2A06': 'Alert Level',
  '2A07': 'Tx Power Level',
  '2A08': 'Date Time',
  '2A0F': 'Local Time Information',
  '2A18': 'Glucose Measurement',
  '2A19': 'Battery Level',
  '2A1C': 'Temperature Measurement',
  '2A1D': 'Temperature Type',
  '2A1E': 'Intermediate Temperature',
  '2A21': 'Measurement Interval',
  '2A22': 'Boot Keyboard Input Report',
  '2A23': 'System ID',
  '2A24': 'Model Number',
  '2A25': 'Serial Number',
  '2A26': 'Firmware Revision',
  '2A27': 'Hardware Revision',
  '2A28': 'Software Revision',
  '2A29': 'Manufacturer Name',
  '2A2A': 'IEEE Regulatory Certification Data',
  '2A2B': 'Current Time',
  '2A31': 'Scan Refresh',
  '2A34': 'Glucose Measurement Context',
  '2A35': 'Blood Pressure Measurement',
  '2A36': 'Intermediate Cuff Pressure',
  '2A37': 'Heart Rate Measurement',
  '2A38': 'Body Sensor Location',
  '2A39': 'Heart Rate Control Point',
  '2A3F': 'Alert Status',
  '2A40': 'Ringer Control Point',
  '2A41': 'Ringer Setting',
  '2A46': 'New Alert',
  '2A49': 'Blood Pressure Feature',
  '2A4A': 'HID Information',
  '2A4B': 'Report Map',
  '2A4C': 'HID Control Point',
  '2A4D': 'Report',
  '2A4E': 'Protocol Mode',
  '2A50': 'PnP ID',
  '2A51': 'Glucose Feature',
  '2A52': 'Record Access Control Point',
  '2A53': 'RSC Measurement',
  '2A54': 'RSC Feature',
  '2A55': 'SC Control Point',
  '2A56': 'Digital',
  '2A5B': 'CSC Measurement',
  '2A5C': 'CSC Feature',
  '2A5D': 'Sensor Location',
  '2A63': 'Cycling Power Measurement',
  '2A65': 'Cycling Power Feature',
  '2A66': 'Cycling Power Control Point',
  '2A67': 'Location and Speed',
  '2A6C': 'Elevation',
  '2A6D': 'Pressure',
  '2A6E': 'Temperature',
  '2A6F': 'Humidity',
  '2A70': 'True Wind Speed',
  '2A71': 'True Wind Direction',
  '2A72': 'Apparent Wind Speed',
  '2A73': 'Apparent Wind Direction',
  '2A74': 'Gust Factor',
  '2A75': 'Pollen Concentration',
  '2A76': 'UV Index',
  '2A77': 'Irradiance',
  '2A78': 'Rainfall',
  '2A79': 'Wind Chill',
  '2A7A': 'Heat Index',
  '2A7B': 'Dew Point',
  '2A7D': 'Descriptor Value Changed',
  '2A7E': 'Aerobic Heart Rate Lower Limit',
  '2A7F': 'Aerobic Threshold',
  '2A80': 'Age',
  '2A85': 'Date of Birth',
  '2A87': 'Email Address',
  '2A8A': 'First Name',
  '2A8C': 'Gender',
  '2A8D': 'Heart Rate Max',
  '2A8E': 'Height',
  '2A90': 'Last Name',
  '2A92': 'Resting Heart Rate',
  '2A96': 'VO2 Max',
  '2A98': 'Weight',
  '2A99': 'Database Change Increment',
  '2A9A': 'User Index',
  '2A9B': 'Body Composition Feature',
  '2A9C': 'Body Composition Measurement',
  '2A9D': 'Weight Measurement',
  '2A9E': 'Weight Scale Feature',
  '2A9F': 'User Control Point',
  '2AA2': 'Language',
  '2AA6': 'Central Address Resolution',
  '2AA7': 'CGM Measurement',
  '2AA8': 'CGM Feature',
  '2AAD': 'Indoor Positioning Configuration',
  '2AAE': 'Latitude',
  '2AAF': 'Longitude',
  '2AB2': 'Floor Number',
  '2AB3': 'Altitude',
  '2AB5': 'Location Name',
  '2AB6': 'URI',
  '2AB7': 'HTTP Headers',
  '2AB8': 'HTTP Status Code',
  '2AB9': 'HTTP Entity Body',
  '2ABA': 'HTTP Control Point',
  '2AC9': 'Resolvable Private Address Only',
};
